{% set name = "fretraj" %}
{% set version = "0.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fretraj-{{ version }}.tar.gz
  sha256: e5026f080e1258d01e62dcd0d13cdeb1a12cfe3900ab6ccfda7c4506349e340b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - "fretraj=fretraj.console:main"
    - "fretraj_gui=fretraj.fretraj_gui:main"
    - "pymol_vis=fretraj.console:pymol_vis"
    - "vmd_vis=fretraj.console:vmd_vis"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - poetry-core
    - pybind11
    - pybind11-abi
  run:
    - python
    - numpy
    - numba
    - pandas
    - importlib-metadata
    - jsonschema
    - mdtraj
    - pyqt
    - tqdm
    - colorama # for tqdm on Windows

test:
  imports:
    - fretraj
  requires:
    - pip
  commands:
    - pip check
    - fretraj --show-config


about:
  home: https://rna-fretools.github.io/
  dev_url: https://github.com/RNA-FRETools/fretraj
  doc_url: https://rna-fretools.github.io/fretraj/
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Predicting FRET with accessible-contact volumes
  description: |
    FRETraj is a Python module for predicting FRET efficiencies by calculating multiple accessible-contact volumes (multi-ACV). It integrates with PyMOL to accelerate FRET-assisted, integrative structural modeling.


extra:
  recipe-maintainers:
    - fdsteffen
